export const BAIRROS_SAO_LUIS = [
  'Anil',
  'Bacanga',
  'Bequimão',
  'Calhau',
  'Camboa',
  'Centro',
  'Cohab',
  'Cohama',
  'Cohatrac',
  'Coroadinho',
  'Coroado',
  'Fátima',
  'Filipinho',
  'Forquilha',
  'Fumacê',
  'Ilhoinha',
  'Itaqui-Bacanga',
  'Jaracaty',
  'João Paulo',
  'Maracanã',
  'Monte Castelo',
  'Olho d\'Água',
  'Outeiro da Cruz',
  'Pão de Açúcar',
  'Parque Vitória',
  'Pedrinhas',
  'Ponta d\'Areia',
  'Porto Grande',
  'Renascença',
  'São Cristóvão',
  'São Francisco',
  'São Marcos',
  'Santa Cruz',
  'Tirirical',
  'Vinhais',
  'Vila Luizão',
  'Outro',
] as const
