export const BAIRROS_SAO_LUIS = [
  'Anil',
  'Angelim',
  'Araçagy',
  'Areinha',
  'Bacanga',
  'Barreto',
  'Bequimão',
  'Boa Vista',
  'Bogéa',
  'Bom Jardim',
  'Calhau',
  'Camboa',
  'Campo do Capim',
  'Centro',
  'Cidade Operária',
  'Cohab',
  'Cohab Anil I',
  'Cohab Anil II',
  'Cohab Anil III',
  'Cohab Anil IV',
  'Cohama',
  'Cohatrac',
  'Coqueiro',
  'Coroadinho',
  'Coroado',
  'Cruz do Passeio',
  'Desterro',
  'Fátima',
  'Filipinho',
  'Forquilha',
  'Fumacê',
  'Genibau',
  'Glacial',
  'Ilhoinha',
  'Itapera',
  'Itaqui-Bacanga',
  'Jaracaty',
  'Jardim América',
  'Jardim Renascença',
  'João Paulo',
  'Liberdade',
  'Maracanã',
  'Maternidade',
  'Monte Castelo',
  'Ney Braga',
  "Olho d'Água",
  'Outeiro da Cruz',
  'Pão de Açúcar',
  'Parque Athenas',
  'Parque das Primaveras',
  'Parque Vitória',
  'Pedrinhas',
  'Planalto Anil',
  'Planalto Bacanga',
  'Planalto Tirirical',
  "Ponta d'Areia",
  'Porto Grande',
  'Praia Grande',
  'Progresso',
  'Quintas do Calhau',
  'Recanto dos Vinhais',
  'Renascença',
  'Sacavém',
  'Santa Cruz',
  'São Cristóvão',
  'São Francisco',
  'São Marcos',
  'Tibiri',
  'Tirirical',
  'Turu',
  'Vila Bacanga',
  'Vila Brasil',
  'Vila Conceição',
  'Vila Embratel',
  'Vila Isabel',
  'Vila Luizão',
  'Vila Maranhão',
  'Vila Nova',
  'Vila Palmeira',
  'Vila Paz',
  'Vinhais',
] as const
